# This file was generated by GoReleaser. DO NOT EDIT.
class GolangciLint < Formula
  desc "Fast linters runner for Go."
  homepage "https://golangci.com"
  version "1.31.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/prakriti07/golangci-lint/releases/download/v1.31.0/golangci-lint-1.31.0-darwin-amd64.tar.gz"
    sha256 "842d2834a57fefe2855d6db6b154dae446110891751f7d3b6f2a5b7f2804bcce"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/prakriti07/golangci-lint/releases/download/v1.31.0/golangci-lint-1.31.0-linux-amd64.tar.gz"
      sha256 "9ebb9d1f3d53872144bde5f05b58f316d51525a0cef75de913397343c26dfd24"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/prakriti07/golangci-lint/releases/download/v1.31.0/golangci-lint-1.31.0-linux-arm64.tar.gz"
        sha256 "5dde38f4c7f35c495adce08853441d0e0028c3006241830a4c43d73cea74efd7"
      else
        url "https://github.com/prakriti07/golangci-lint/releases/download/v1.31.0/golangci-lint-1.31.0-linux-armv6.tar.gz"
        sha256 "31c12374b8588b27b78a8a9ffc69025200eb42ec486dd9f3400cca6ab08463bc"
      end
    end
  end

  def install
    bin.install "golangci-lint"
    output = Utils.popen_read("#{bin}/golangci-lint completion bash")
    (bash_completion/"golangci-lint").write output
    output = Utils.popen_read("#{bin}/golangci-lint completion zsh")
    (zsh_completion/"_golangci-lint").write output
    prefix.install_metafiles
  end

  test do
    system "#{bin}/golangci-lint --version"
  end
end
