# This file was generated by GoReleaser. DO NOT EDIT.
class GolangciLint < Formula
  desc "Fast linters runner for Go."
  homepage "https://golangci.com"
  version "1.32.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/prakriti07/golangci-lint/releases/download/v1.32.0/golangci-lint-1.32.0-darwin-amd64.tar.gz"
    sha256 "e9b82aa31db30385e7368fe4bf86d1446ca74e40f2ff7a6f5895213f9f8ad234"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/prakriti07/golangci-lint/releases/download/v1.32.0/golangci-lint-1.32.0-linux-amd64.tar.gz"
      sha256 "e284b41dd0c580c5310420584bad98d3a7431c108617ef4926fa38c5b5eeaaa2"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/prakriti07/golangci-lint/releases/download/v1.32.0/golangci-lint-1.32.0-linux-arm64.tar.gz"
        sha256 "7468462220d1575a7fcace320b3c1c940348d9c7e4cc8ebae9f7b19956e89b25"
      else
        url "https://github.com/prakriti07/golangci-lint/releases/download/v1.32.0/golangci-lint-1.32.0-linux-armv6.tar.gz"
        sha256 "5545a2f728faec7d1d835228e4bedc4612ddf7bb05eaf1734e41f817703585ec"
      end
    end
  end

  def install
    bin.install "golangci-lint"
    output = Utils.popen_read("#{bin}/golangci-lint completion bash")
    (bash_completion/"golangci-lint").write output
    output = Utils.popen_read("#{bin}/golangci-lint completion zsh")
    (zsh_completion/"_golangci-lint").write output
    prefix.install_metafiles
  end

  test do
    system "#{bin}/golangci-lint --version"
  end
end
